#!/bin/bash

current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
target_branch=$1

if [ "$current_branch" = "main" ] && [ "$target_branch" != "main" ]; then
    echo "エラー: mainブランチから直接新しいブランチを作成することは禁止されています。developブランチから作成してください。"
    exit 1
fi

exit 0
