#!/bin/bash

protected_branch='main'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $current_branch = $protected_branch ]; then
    echo "エラー: 直接mainブランチにプッシュすることは禁止されています。developブランチを使用してください。"
    exit 1
fi

exit 0
